export const TableActionTypes = {
    TABLE_RESIZE: 'TABLE_RESIZE',
    MODIFY_CELL_DATA: 'MODIFY_CELL_DATA',
    APPLY_STYLE: 'APPLY_STYLE',
    CHANGE_STYLE: 'CHANGE_STYLE',
    TITLE_MODIFY: 'TITLE_MODIFY'
}
